### ISSUE TITLE
unable to add my name to contributors list

### ISSUE THREAD

**Issue by vsaikm** [zero-to-mastery/start-here-guidelines#4737]
After I have done the pull request ,then i observed that my name is not  been added to the list.

**Comment by nishanthvg** [comment]
even i faced the same problem

**Comment by rishik-00** [comment]
They might have not merged your pull request yet

**Comment by rsamuell** [comment]
I'm having the same issue.  Folllowed along with GitHub videos online but it is not working.  Saying that I am denied to commit files to the repo.

**Comment by rsamuell** [comment]
Permission to zero-to-mastery/start-here-guidelines.git denied

**Comment by meenakshisharma2367** [comment]
I had merged the pull request still my name is not on the list,Please review.

**Comment by SagarPalyal** [comment]
Once your merge request will get approved by reviewer/admin, then your name will come up in the list.

**Comment by meenakshisharma2367** [comment]
Okay

**Comment by adityas21420** [comment]
I have added my name to the contributor list by using a pull request but my name is still not added to the original file,

**Comment by zainsadaqat** [comment]
i think the management team didn't check our requests

**Comment by pradhuman-web** [comment]
Unable to add my name to the list of contributor list even i have the organization icon to my profile please help me(;

**Comment by phuctoan1495** [comment]
I got the same problem here. I was merged my pull request but cannot find my name in the CONTRIBUTORS file

**Comment by Reny10** [comment]
I have the same issue.

**Comment by KhushiGangopadhyay** [comment]
i am unable to add my name , its showing permission denied unable to access the site

**Comment by Aiswarya2020** [comment]
Me too, same issue.

**Comment by MattCSmith** [comment]
If you are receiving ``ERROR: Permission to zero-to-mastery/start-here-guidelines.git denied ...` 
Double check that you forked this repo first. 
You will get that error if skipped that step and jumped straight to cloning the repo.

**Comment by sophiabrandt** [comment]
I have updated the [README.md](README.md) with instructions on how to fork the repository. I hope that helps.

**Comment by WebDeveloper-Zacchaeus** [comment]
There appears to be a merge conflict ? Is it because I changed my username ? I tried to resolve the issue as well.

**Comment by serenadinh** [comment]
Same here. After I forked the master, I can't see the Clone button.

**Comment by Gobinath24** [comment]
I can't pull the request

**Comment by WebDeveloper-Zacchaeus** [comment]
> Same here. After I forked the master, I can't see the Clone button.

Clone won't be available for private data ! There must be a "CODE" instead.

**Comment by WebDeveloper-Zacchaeus** [comment]
> I can't pull the request

You need to pull the origin first then push your entry. Mine got resolved in that way.

**Comment by sophiabrandt** [comment]
Please follow the instructions in the `README`. Everything is explained there. 
For merge conflicts, follow the instructions from the Zero Bot.

I will close this issue because it contains a mish-mash of errors.

If something is still not working, you can open a new issue here or ask on Discord.
